Simulate failed build
Signed-off-by: Georgios Ntoutsos <gntouts@nubificus.co.uk>

diff --git a/.github/workflows/parent-release.yaml b/.github/workflows/parent-release.yaml
--- a/.github/workflows/parent-release.yaml
+++ b/.github/workflows/parent-release.yaml
@@ -150,10 +150,10 @@ jobs:
         else
           echo "No artifacts were downloaded"
         fi
-    - name: Simulate successful build
+    - name: Simulate failed build
       run: |
-        echo "Simulating a successful build for testing"
-        exit 0
+        echo "Simulating a failed build for testing"
+        exit 1
     - name: Upload artifacts to parent release
       uses: softprops/action-gh-release@v2
       with:
